### ISSUE TITLE
SyntaxError: Unexpected token ) at RUNTIME_DIR/apps/server/server.js:35

### ISSUE THREAD

**Issue by code-hunger** [Pomax/mahjong#23]
Here is the output, RUNTIME_DIR is where the repository is cloned:
http://pastebin.com/25sxyhfx
And that's the npm-debug.log file:
http://pastebin.com/Zx5BJB1S
Note: on `npm install` I do also get a warning:
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11```

**Comment by Pomax** [comment]
The error you're showing is about node not understanding ES6 arrow notation, which is only the case for ancient versions of Node.js Upgrade your Node.js to the current LTS or Stable version of Node.js.

The npm install warnings are irrelevant; it's just a notice that fsevents won't work for windows, which is true, but has no impact on any of the code doing what it needs to do.

**Comment by code-hunger** [comment]
Yes, I'm on my own computer with arch linux:
```
$ pacman -Q nodejs
nodejs 5.10.0-1
```
Is there anything I should do except `npm install` and `npm start`?

**Comment by Pomax** [comment]
no, those are the only steps necessary. I suspect you're running into the hiliarious situation where package.json expects your node runtime to be called `node`, not `nodejs`. Most linux/unix have fixed this problem by now, but some still have a package for ham radio or something that gets to use the `node` name, which isn't the most useful thing. If your node runtime is not `node` but `nodejs` or something else, you'll need to modify the `scripts` section in package.json to use your runtime command instead.

**Comment by code-hunger** [comment]
Nope, the command is `node` (`nodejs` doesn't exist). If I do `var x = ()=>1;` in the cli I get three dots, after typing a dot I'm getting `invalid REPL keyword`.

**Comment by Pomax** [comment]
that's pretty impressive, your node is node doing what it should be. Is it a custom build instead of an official build? The thing you're seeing is a modern version of node, officially with ES6 support, breaking down over pretty much the very first ES6 feature that ever landed in it (arrow notation).

See what it does in a manual test if you say `node --harmony`. That should (at least, used to, I'm not sure if 5.10 even still has it since ES6 is supposed to just work) explicitly turn on modern JS parsing rules.

**Comment by code-hunger** [comment]
Got it working, tanks!
```
$ node --harmony
> var x = () => 1;
undefined
> x();
1
> 
```
Solved it by adding the flag to the node command in `package.json`.
Unfortunately another problem came up:
```
mahjong/apps/server/lib/game/game-manager.js:26
        socket.emit("server:reset", { games });
                                            ^
SyntaxError: Unexpected token }
```
I suppose I have to enable some feature like above for that to work? After some research I found out this is called "destructuring". [This stackoverflow answer](http://stackoverflow.com/a/17379714/3132718) says to use `--harmony_destructuring` flag but I get a node error: `bad option: --harmony_destructuring`. Tried updating node to `5.10.1-1`, no effect.
Nor it is listed in `--v8-options`. 
I installed node from the official repositories. Might be some problem there which I don't believe much in since I can't find it as a bug in google.

**Comment by Pomax** [comment]
Hm, another option might be to bash-alias `node` as `node --harmony` (so, specifically to your bash profile) using `alias node="node --harmony"`, but that leaves the question about why your version of Node is not running with the correct settings (5.* has, officially at least, all harmony flags turned on)
