### ISSUE TITLE
Syntax error at socket.emit("server:reset", { games });

### ISSUE THREAD

**Issue by code-hunger** [Pomax/mahjong#24]
After solving the previous issue #23 here is what I get:
```
mahjong/apps/server/lib/game/game-manager.js:26
        socket.emit("server:reset", { games });
                                            ^
SyntaxError: Unexpected token }
```
I suppose I have to enable some feature like above for that to work? After some research I found out this is called "destructuring". [This stackoverflow answer](http://stackoverflow.com/a/17379714/3132718) says to use `--harmony_destructuring` flag but I get a node error: `bad option: --harmony_destructuring`. Tried updating node to `5.10.1-1`, no effect.
Nor it is listed in `--v8-options`. 
I installed node from the official repositories. Might be some problem there which I don't believe much in since I can't find it as a bug in google.

**Comment by Pomax** [comment]
It sounds suspiciously like you're not getting the right version of node, or a version that is compiled with very different settings from everyone else, especially if that flag doesn't work: that feels like you're getting an older version of Node while whatever package manager you're using pretends it's the latest. 

One thing you can try is to install [`nvm`](https://github.com/creationix/nvm) (either manually or through `npm install -g nvm`), and then use that to manage your node versions. [Make it install and then `use` 5.10](https://github.com/creationix/nvm#usage) and see if that helps

**Comment by code-hunger** [comment]
Yep, installed 5.10 manually and now it starts without errors!

**Comment by Pomax** [comment]
nice!
