### ISSUE TITLE
Suggestion: Having a fullscreen button shortcut.

### ISSUE THREAD

**Issue by lexterror** [Pomax/mahjong#67]
Hi Pomax,

I was thinking it would be a good idea to add a "fullscreen" button. I've been using a browser since forever but never really occurred to me to use the "fullscreen" button from the browser menu until now to be able to see the full game board. I usually own a 1366x768px monitor for laptops. I think it's a very common screen resolution that a lot of people have, and unless you click the "fullscreen" browser button from the menu you can't see the full game board. Also, in the future if you decided to go "vector" you could have it "enlarge" as well so that it would fit any screen by just pressing on your "fullscreen" button.

Thank you.

**Comment by Pomax** [comment]
I can't say I know anyone with a laptop that's less than 1080p at this point, but I'd definitely go with "you already have a fullscreen button". Webpages should not reimplement functionality that every browser already has.

**Comment by lexterror** [comment]
Pomax, are you saying there's a MJ game somewhere that's private that no one has access  to? Im not asking for details...
