### ISSUE TITLE
Where to find the "Show bot play suggestions" during the game

### ISSUE THREAD

**Issue by chandajj** [Pomax/mahjong#69]
I turn on the "Show bot play suggestions" at setting. What types of suggestions can I get? From my understanding is like which tiles I should discard?

I didn't find any suggestions during play. Maybe I missed it? Or it has another meaning I understand wrong.

Thank you for your answer!

**Comment by Pomax** [comment]
They're color suggestions, so for instance here, we see the bot suggesting that I discard north by marking it with a black top border:

![image](https://user-images.githubusercontent.com/177243/147374755-2f7d6c9e-a035-4f9b-a305-96c3a6deebe3.png)

If you mouse-over and wait, you will see the title reflect this:

![image](https://user-images.githubusercontent.com/177243/147374804-020d5ac9-c416-4f98-a28b-b5d22b9f2e73.png)

And here it's suggesting I claim the discard by giving the discard a different color:

![image](https://user-images.githubusercontent.com/177243/147374790-64237b16-e40f-4122-9b91-81511385125b.png)

That said, if you just want to play MJ, I have been working on a better implementation for the last two years that is now up and available over on https://letsplaymahjong.ca (still free, until I get to a point where it's so polished that actually charging a small fee even makes sense, which won't be any time soon). With the benefit that you can play with your friends (if you want) or single player if you just want to play some MJ.

(note that the keyboard controls are slightly different, but also make a bit more sense)

**Comment by chandajj** [comment]
Thank you so much!
